### ISSUE TITLE
Doesn't work inside a VirtualBox VM

### ISSUE THREAD

**Issue by benintech** [kazysmaster/gnome-shell-extension-lockkeys#106]
It works fine in my laptop (bare metal), Debian 11 / Gnome 3.38.

But it doesn't work inside a VirtualBox VM, with exactly the same OS (Debian 11, Gnome 3.38). 

I tested CAPSLOCK, I don't have a numpad, so I don't know how NUMLOCK behaves.

In details :

On the host, (bare metal), it works as I expect it too :
- Hitting CAPSLOCK toggles the indicator
- Pressing SHIFT has no effect whatsoever

In a VM however, the behavior is different, and it reacts on both CAPSLOCK and SHIFT :
1/ CAPSLOCK is OFF
2/ I hit CAPSLOCK, the indicator blinks but turns back to the OFF state, even though CAPSLOCK is on.
3/ I then hit SHIFT, and the indicator turns ON
4/ If I hit SHIFT again, nothing happens (the indicator stays ON)
5/ And if I hit CAPSLOCK again, it goes back to state 1 (CAPSLOCK OFF)
6/ If CAPSLOCK is OFF and I hit SHIFT, nothing happens

**Comment by kazysmaster** [comment]
Hi, sorry, but I'm afraid that there is not much I can do here - key events are handled by gnome libraries. I'm not sure if keyboard  polling (which I'm very reluctant to implement) would fix that.
