### ISSUE TITLE
GNOME 44

### ISSUE THREAD

**Issue by yochananmarqos** [kazysmaster/gnome-shell-extension-lockkeys#110]
With GJS 1.75.90 and GNOME Shell 44.rc, the extension no longer works.

```
imports.gi.Gdk.Keymap is undefined
```

**Comment by mokilcde** [comment]
Same here

**Comment by kazimierasvaina-cujo** [comment]
ack

**Comment by kazysmaster** [comment]
ack

**Comment by kazysmaster** [comment]
was that x11 session? can you check wayland?

**Comment by mokilcde** [comment]
x11 session

**Comment by mokilcde** [comment]
The same on `wayland`

**Comment by kazysmaster** [comment]
Pls try latest from master. Will need gtk 4.10.2 for extension preferences to work.

**Comment by mokilcde** [comment]
Thanks for that. It works also for me using `gtk` `4.10.0` on `Debian SID / experimental` (4.10.0+ds-2)

**Comment by kazysmaster** [comment]
probably I was just unlucky to hit https://gitlab.gnome.org/GNOME/gtk/-/issues/5644

**Comment by yochananmarqos** [comment]
Works fine with Gtk 4.10.0 on GNOME 44.rc. 4.10.2 isn't tagged yet.

**Comment by kazysmaster** [comment]
Does anyone has Gnome 3.xx on some vm? I would love to see if recent changes did not break older gnome releases.

**Comment by kreaninw** [comment]
I am also having this issue. The one in http://extensions.gnome.org/ is outdated. The latest commit on GitHub works with GNOME 44.

**Comment by yochananmarqos** [comment]
This has been fixed for awhile, closing.
