### ISSUE TITLE
Error in 3.10

### ISSUE THREAD

**Issue by mightymouse2045** [kazysmaster/gnome-shell-extension-lockkeys#14]
Hi - this is working in 3.10 but just noticed getting this error:

** Message: JS WARNING: [~/.local/share/gnome-shell/extensions/lockkeys@vaina.lt/prefs.js 55]: assignment to undeclared variable id

Refers to:

	for (id in values) {
		widget.append(id, values[id]);
	}
	widget.set_active_id(settings.get_string(key));

**Comment by kazysmaster** [comment]
It is already fixed.
