### ISSUE TITLE
Feature Request: Add option for default setting for both num and caps lock

### ISSUE THREAD

**Issue by jorenverspeurt** [kazysmaster/gnome-shell-extension-lockkeys#21]
My Numlock is off by default but I would like it to be on and now I have to push the button in the top bar every time my laptop starts up, which is quite annoying. I added a call to the onclick for the Numlock button at the end of the initialization in the code on my machine but that's a bit dirty... That toggles it every time I log out and in or restart Gnome.

**Comment by JonathonReinhart** [comment]
There's probably an option in your BIOS setup for this as well.

**Comment by kazysmaster** [comment]
I just recently removed dependency of caribou package (it was obsoleted by by gnome) which somewhat provided a way to control numlock and capslock state. It make this feature out of scope now, sorry. 

Of course patches are welcome if you find a way to control keyboard state using some other library.
