### ISSUE TITLE
Icon licensing

### ISSUE THREAD

**Issue by ikeydoherty** [kazysmaster/gnome-shell-extension-lockkeys#25]
Hi, I cannot find any information within this repository detailing the license for either the code or the icons.
Assuming your icons are under suitable license, with your permission I would like to reuse them within the Budgie Desktop for our own "lock keys" applet.

Thanks :)

**Comment by JonathonReinhart** [comment]
FYI: It appears that this issue can be closed.

**Comment by ikeydoherty** [comment]
Indeed. It appears there is no information available on the licensing.
