### ISSUE TITLE
Add installation procedure

### ISSUE THREAD

**Issue by JonathonReinhart** [kazysmaster/gnome-shell-extension-lockkeys#26]
Considering this project has no `autogen.sh` it might be useful to add a manual installation procedure to README.md, for those not familiar with GNOME plugins.

**Comment by kazysmaster** [comment]
Ok, as you probably know there's no building involved and installation it's a matter of copy paste.

**Comment by JonathonReinhart** [comment]
I figured it out, yes. But it took surprisingly long to learn what
directory I needed to copy the files into. Try Googling for "install gnome
shell extension manually".
