### ISSUE TITLE
Icon LICENSE 

### ISSUE THREAD

**Issue by LeoIannacone** [kazysmaster/gnome-shell-extension-lockkeys#27]
Hi,

I would like to use your icons for one of my projects.. can you please add some LICENSE file so I can give you credits ?

Thanks in advance,

L.

**Comment by kazysmaster** [comment]
I just added a GPL v2 LICENSE file, is that ok ? I think http://extensions.gnome.org requires GPL compatible license.

**Comment by LeoIannacone** [comment]
Thank you!
