### ISSUE TITLE
Not working under Wayland

### ISSUE THREAD

**Issue by seamlik** [kazysmaster/gnome-shell-extension-lockkeys#32]
If entering "GNOME on Wayland" session, this extension fails to detect the state and its changes of Caps Lock and Num Lock. Manually switching the state by clicking the extension's switcher won't affect the real state of two keys.

I am in Debian stretch/testing with GNOME 3.18.

**Comment by michaellass** [comment]
I observed the same behavior on Arch Linux. Interestingly if you press Caps Lock and then switch into an application that runs under Xwayland the status icon refreshes and shows the correct state. But as long as you stay in pure wayland applications the icon does not change.

**Comment by kazysmaster** [comment]
Thank you for the bu report. I did little research. I think I won't be able to fix this issue until the https://bugzilla.gnome.org/show_bug.cgi?id=740969 is resolved.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by fernandopsilveira** [comment]
Won't fix :-(
https://bugzilla.gnome.org/show_bug.cgi?id=740969#c6

**Comment by SalahAdDin** [comment]
what?

**Comment by kazysmaster** [comment]
@Lilalas  it seems that the extension was crashing because of caribou package. Please install the caribou package or the extension form github because it has the fix already implemented.

**Comment by Lilalas** [comment]
@kazysmaster No, that’s not true, I have `caribou` installed. Before I installed `caribou`, the extension wasn’t even booting up. With `caribou`, it works fine on **X11**, but it crashes on **Wayland**.

I'll check out the new version if I find the time to do so.

**Comment by Lilalas** [comment]
I have manually updated to version 26 to check whether it fixes this issue. It does not.

However, I take back the crashing; this seems to have been a temporary issue for me. It’s now exactly like @seamlik describes: The extension fails to detect the lock keys’ state; manually switching the state by clicking the extension’s switcher does nothing (the switches remain deactivated).

**Comment by kazysmaster** [comment]
I added support for wayland in master. Please test the extension from github.
