### ISSUE TITLE
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

### ISSUE THREAD

**Issue by g0dd4rd** [kazysmaster/gnome-shell-extension-lockkeys#33]
Description:
This is a minor issue I noticed in Fedora 23 (IDK if it applies to earlier versions). 

Steps to reproduce:
1. gnome-shell-extension-prefs lockkeys@vaina.lt
2.
3.

Actual results:
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

Expected results:
Clean execution without warnings

Note:
This is related to given extension as not all extensions print this warning.

**Comment by kazysmaster** [comment]
probably irrelevant by now. closing
