### ISSUE TITLE
Gjs-Message: JS WARNING: assignment to undeclared variable id

### ISSUE THREAD

**Issue by g0dd4rd** [kazysmaster/gnome-shell-extension-lockkeys#34]
Description:
This is a minor issue I noticed in Fedora 23 (IDK if it applies to earlier versions). 

Steps to reproduce:
1. gnome-shell-extension-prefs lockkeys@vaina.lt
2.
3.

Actual results:
Gjs-Message: JS WARNING: [/home/jprajzne/.local/share/gnome-shell/extensions/lockkeys@vaina.lt/prefs.js 56]: assignment to undeclared variable id

Expected results:
Clean execution without warnings

Note:
This is related to given extension as not all extensions print this warning.

**Comment by kazysmaster** [comment]
probably irrelevant by now, closing.
