### ISSUE TITLE
Update for 3.18?

### ISSUE THREAD

**Issue by magthe** [kazysmaster/gnome-shell-extension-lockkeys#35]
Can we get an update for 3.18, please?

**Comment by magthe** [comment]
Just adding `"3.18"` to the shell versions list seems to be enough.  It would be nice with a proper release of it though :)

**Comment by kazysmaster** [comment]
It is really strange, because since 23rd version the the metadata.json says that gnome 3.18 is supported:
https://extensions.gnome.org/review/5334

**Comment by magthe** [comment]
Very strange.  I checked it on the Gnome extensions site yesterday and was told there was no version usable with Gnome 3.18.  When I go to the site today there's an update button available.

Well, it seems to be working even for me now :)
