### ISSUE TITLE
Make the indicator work while in the overview mode.

### ISSUE THREAD

**Issue by ghost** [kazysmaster/gnome-shell-extension-lockkeys#42]
Hi,

Toggling the caps lock key while in the overview mode doesn't toggle the 'A' indicator in the top panel. The toggling only works upon exiting the overview mode.

Thanks.

**Comment by ahrherrera** [comment]
Sometimes it does not listen for status change, using Fedora 25 on Gnome Shell 3.22.3

Hope owner can help.

**Comment by kazysmaster** [comment]
I assume that running gnome shell on wayland, because on x11 it works as expected. On wayland it works only for xwaylnad applications, by it does not for pure wayland apps like nautilus.

**Comment by bmansurov** [comment]
@kazysmaster I haven't checked X11, but you're right that this behavior is observed in Wayland.

**Comment by ahrherrera** [comment]
@kazysmaster yes, that's right. I am running Fedora 25 on Wayland. Not all apps is working.

**Comment by kazysmaster** [comment]
closing. please file a new issue if that's still relevant.
