### ISSUE TITLE
Add F-Lock

### ISSUE THREAD

**Issue by joestrong** [kazysmaster/gnome-shell-extension-lockkeys#43]
Add an F-Lock feature to switch between normal function key usage, and special usage

Example: On apple keyboards, the F keys affect screen brightness, volume etc. Switching the F-Lock would make them use their normal usage.

**Comment by kazysmaster** [comment]
good suggestion I'm still keeping that in mind... I'll try to implement as soon I spot a support from gtk/gdk libs.

**Comment by kazysmaster** [comment]
support for this probably will not be implemented.
