### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by dirosis** [kazysmaster/gnome-shell-extension-lockkeys#44]
Hello, I have translated the extension in greek. Where should I upload it

**Comment by kazysmaster** [comment]
Hi, the best way is to branch the extension and make pull request. But you can send me to kazimieras.vaina@gmail.com. I will integrate the translation in the near future.

**Comment by dirosis** [comment]
Hello, I send it to you via email as i don't really now how to create a pull request
