### ISSUE TITLE
Icons in notifications

### ISSUE THREAD

**Issue by Maestroschan** [kazysmaster/gnome-shell-extension-lockkeys#45]
in _prepareSource, this._source.createNotificationIcon doesn't work (or even exist ? with Gnome 3.22) and St.IconType neither.

I suggest something like
```
this._source.createIcon = function() {
	return new St.Icon({ icon_name: icon_name+'-symbolic'	});
};
```
but i can't tell what would be the behavior of this syntax with olders version of Gnome Shell

**Comment by kazysmaster** [comment]
Thanks for the suggestion. I didn't test the extension yet on gnome 3.22

**Comment by kazysmaster** [comment]
it's gnome 3.26 and it seems fine without it. I'll leavi it this way.
