### ISSUE TITLE
Indicator doesn't work when lock keys are pressed in a bash terminal window

### ISSUE THREAD

**Issue by lopezbj** [kazysmaster/gnome-shell-extension-lockkeys#46]
When the CapsLock key is pressed inside a bash terminal, the indicator does not notify. Only when the terminal window is closed, does the indicator notify about the last status of the CapsLock. This issue was encountered on Fedora 27 under Wayland.

**Comment by glats** [comment]
Same issue here.
Plus it happen when you are in nautilus and other thing programs from gnome

**Comment by kazysmaster** [comment]
Hi, I am aware of this issue. The indicator works only for xwayland windows.

**Comment by lopezbj** [comment]
Alright, thanks for looking into this. I tried using GNOME under Xorg and the indicator works well.

**Comment by kazysmaster** [comment]
fixed.
