### ISSUE TITLE
Update to gnome 3.28

### ISSUE THREAD

**Issue by fmac95** [kazysmaster/gnome-shell-extension-lockkeys#48]
Hello, can you update this extension for the gnome 3.28 on ubuntu 18.04 lts

**Comment by Stupendoussteve** [comment]
Install Caribou and it will work again.

**Comment by sergiohgz** [comment]
As @Stupendoussteve said, with Caribou installed it works :+1:

**Comment by ivanlechat** [comment]
That will only work if you are running Ubuntu 18.04? I am Using Solus with the Gnome DE and is also working perfectly fine on 3.28.1. Thank you for the great work!

**Comment by Stupendoussteve** [comment]
It is needed on Fedora as well. Probably Solus installs it by default.

**Comment by wangxa** [comment]
In Fedora 28, the caribou packages (0.4.21) have been marked as obsolete package. The update will automatically remove caribou, so the extension will not work any more.

**Comment by kazysmaster** [comment]
I removed usage of caribou. The metadata.json has been updated. The extension has been submitted for a review.
