### ISSUE TITLE
Doesn't work in Fedora 28.

### ISSUE THREAD

**Issue by nas-faq** [kazysmaster/gnome-shell-extension-lockkeys#49]
Thanks for nice work.
I used the extension with Fedora 27 successfully.
But after upgrade to Fedora 28 the extension stopped to run.

**Comment by kazysmaster** [comment]
Please install carobu packages or use the version from github.

**Comment by nas-faq** [comment]
> **carobu** packages
Can you please elaborate, what do you mean?

**Comment by kazysmaster** [comment]
oops, misspelled that package name. What I meant was:
caribou
caribou-gtk2-module
caribou-gtk3-module
