### ISSUE TITLE
Load fails on Fedora 28

### ISSUE THREAD

**Issue by tuxmaster** [kazysmaster/gnome-shell-extension-lockkeys#51]
When I try to load the extensions it will fails with:
Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
gnome-shell[8148]: Extension "lockkeys@vaina.lt" had error: Error: Requiring Caribou, version none: Typelib file for namespace 'Caribou' (any version) not found

**Comment by kazysmaster** [comment]
Thank's for the info. I will look to that. 
Regarding the "Requiring Caribou, version none: Typelib file for namespace 'Caribou' (any version) not found" please use the version from github as I dropped requirement for Caribou.

**Comment by tuxmaster** [comment]
Yes the last download from the master will fix it.
Thanks.
