### ISSUE TITLE
Indicator missing on login and lock screens

### ISSUE THREAD

**Issue by colans** [kazysmaster/gnome-shell-extension-lockkeys#52]
While the indicators show up fine when logged in, they don't show up:

1. On the login screen, and
2. On the unlock screen when the session is locked.

This functionality is most helpful when entering a password.

Please add support for this.  Or is there another way to show a Num Lk indicator on these screens?

**Comment by eman1986** [comment]
I don't think you can do this as you can technically switch DE while on the login screen so gnome's extension engine is not loaded
