### ISSUE TITLE
Change icons ? Or have them white ?

### ISSUE THREAD

**Issue by Coeur-Noir** [kazysmaster/gnome-shell-extension-lockkeys#53]
Hi,

with Adapta gtk and gnome-shell theme icons are too dark : 
![lockkey](https://user-images.githubusercontent.com/1895947/45258789-d431ed00-b3be-11e8-8164-ed8f3b9a9449.png)

I've tried to modify their color ( to full white ) in inkscape, but no change.

Any hints ?
_______________
edit : 

…the icons displayed in panel are not the ones located in
`~/.local/share/gnome-shell/extensions/lockkeys@vaina.lt/icons/`
???

Ubuntu 18.04 here.

**Ok, sorry. That depends on icon theme, so Papirus-Dark instead of Papirus did the trick.**

**Comment by kazysmaster** [comment]
ok, probably theme icons overrides icon located in the ~/.local/share/gnome-shell/extensions/lockkeys@vaina.lt/icons
