### ISSUE TITLE
Lock key doesn't work on libreoffice

### ISSUE THREAD

**Issue by SimoBonfo** [kazysmaster/gnome-shell-extension-lockkeys#58]
When the focus is on a Libreoffice window, the extension doesn't refresh it's state when Caps lock or Num lock are pressed.

**Comment by kazysmaster** [comment]
Does it happen in wayland session or in x11 session ?

**Comment by SimoBonfo** [comment]
I'm using Wayland on Fedora 29

**Comment by kazysmaster** [comment]
I added support for wayland in master. Please test the extension from github.

**Comment by kazysmaster** [comment]
it requires fedora 31 at least.
