### ISSUE TITLE
Toggles Disabled on Ubuntu 18.10

### ISSUE THREAD

**Issue by ghost** [kazysmaster/gnome-shell-extension-lockkeys#59]
The toggles in the menu are grayed out, and are not toggleable. The functionality as a basic indicator still works, but personally I've mostly used it to toggle them and this is a large issue. Any ideas why this is happening? Is it intentional?

**Comment by kazysmaster** [comment]
It is intentional. Toggles didn't work well - sometimes they didn't change key state of an actual keyboard, so I just removed the functionality. Sorry :(
