### ISSUE TITLE
Icons not picked up from icon theme after update for GNOME 3.32

### ISSUE THREAD

**Issue by drakkar1969** [kazysmaster/gnome-shell-extension-lockkeys#60]
With the update for GNOME 3.32, icons no longer change with the icon theme, would be great if we could get themeable icons back.
Thanks!

**Comment by kazysmaster** [comment]
What icon theme provides custom icons for this extension ?

**Comment by drakkar1969** [comment]
For example the Papirus icon theme does

**Comment by kazysmaster** [comment]
the github version should pick icons from recent papirus theme.
