### ISSUE TITLE
no longer working  GNIME 3.34 + Wayland

### ISSUE THREAD

**Issue by jjgalvez** [kazysmaster/gnome-shell-extension-lockkeys#62]

**Comment by jjgalvez** [comment]
under wayland with Gnome 3.34 the indicator does not register when the state of caps or num lock changes, unless you are in an X-window

**Comment by darylf** [comment]
I just updated to Fedora 31 and this extension no longer works. I'm guessing it's the same bug as what's reported here. I'm not sure how to produce logs that are helpful, but please advise how I can help

**Comment by gitmatt19** [comment]
Centos8 seems to have the same issue. No changes shown.

**Comment by kazysmaster** [comment]
It is a know issue that the extension doesn't work on wayland. Actually It works when non native wayland application is in focus, but that's not very satisfying. 
 I don't have a fix for that at all. Sorry.

**Comment by jjgalvez** [comment]
may not be satisfying but it's a wayland issue not an issue with you're code necessarily. Have to wait to see if Wayland adds support for it

**Comment by lastweakness** [comment]
No fix for this is coming any time soon... Sad how big a reason this has been for me using KDE imore often than GNOME.

**Comment by jjgalvez** [comment]
> No fix for this is coming any time soon... Sad how big a reason this has been for me using KDE imore often than GNOME.

are you using Wayland with KDE? if so I wonder how KDE is able to figure out when the caps lock and number key changes. I thought this was more of a wayland issue not a gnome vs kde  issue

**Comment by kazysmaster** [comment]
I added support for wayland in master. Please test the extension from github.

**Comment by gitmatt19** [comment]
Tried the update on CentOS 8.1 and the addon seems to work now 
THANKS !

**Comment by liZe** [comment]
It works, thanks a lot!

I had to add this quick and dirty patch to make it work on 3.36:
```patch
diff --git a/lockkeys@vaina.lt/extension.js b/lockkeys@vaina.lt/extension.js
index e602ba3..2c332b5 100644
--- a/lockkeys@vaina.lt/extension.js
+++ b/lockkeys@vaina.lt/extension.js
@@ -12,7 +12,7 @@ const PopupMenu = imports.ui.popupMenu;
 const MessageTray = imports.ui.messageTray;
 
 const Keymap = parseFloat(imports.misc.config.PACKAGE_VERSION) >= 3.34 ?
-               imports.gi.Clutter.get_default_backend().get_keymap() :
+               imports.gi.Clutter.get_default_backend().get_default_seat().get_keymap() :
                imports.gi.Gtk.Keymap.get_default();
 
 
@@ -28,6 +28,12 @@ const STYLE_BOTH = 'both';
 const STYLE_SHOWHIDE = 'show-hide';
 const NOTIFICATIONS = 'notifications';
 
+Gtk.IconTheme.get_default = function() {
+    let theme = new Gtk.IconTheme();
+    theme.set_custom_theme(St.Settings.get().gtk_icon_theme);
+    return theme;
+};
+
 let indicator;
 
 function main() {
```

**Comment by jjgalvez** [comment]
just tested on Arch with Gnome 3.36 and applying liZe's patch it's working now! Thank you

**Comment by jjgalvez** [comment]
Pulled the latest code this morning and for it wit work with Gnome 3.36 and Arch I had to apply the patch as described by liZe otherwise it would not work. Not sure if it's an Arch thing or a Gnome 3.36 thing

**Comment by kazysmaster** [comment]
intresting, I don't have gnome 3.36 yet. It seems it needs another if statement.

**Comment by CBiX** [comment]
Extension stopped working on Gnome 3.36/X11/Arch. When applying the patch above to the latest master @ 6eca092 I can activate the extension again, but the dropdown doesn't have an icon (making it invisible) and also doesn't react to the lock keys.
If I can help debugging and fixing this please guide me in the right direction, I have lots of experience in JS but never managed to wrap my head around the Gnome extensions platform :D

**Comment by kazysmaster** [comment]
Please try the extension from gnome-3.36 branch.

**Comment by CBiX** [comment]
The gnome-3.36 branch works perfectly again, thanks!

**Comment by jjgalvez** [comment]
> Please try the extension from gnome-3.36 branch.

Works Great! Thank you
