### ISSUE TITLE
Feature request: additional option for OSD notification (like volume change)

### ISSUE THREAD

**Issue by linuxam** [kazysmaster/gnome-shell-extension-lockkeys#70]
I'm not good at typing and I have to look down (at the keyboard) a lot. Because of this I often miss the notification when I accidentally hit caps lock. 
I would really like to see more prominent notification closer to the bottom edge of the screen.  Notification like the one for volume change would fit perfectly.
I don't know how this can be done via gjs but I'm able to do it via `gdbus call` from terminal.
End result would be something like this (I executed the `gdbus call` and hit the caps lock at the same time):
![LockKeys_OSD-notification](https://user-images.githubusercontent.com/37160382/75092913-13390b80-557d-11ea-8396-ad3d7b9c5b0d.png)

Command used to achieve this is:
`gdbus call --session --dest 'org.gnome.Shell' --object-path '/org/gnome/Shell' --method 'org.gnome.Shell.ShowOSD' "{'icon': <'/home/uros/.local/bin/capslock-enabled-argos-top.svg'>, 'label': <'Caps Lock On'>}"`
Icon can referred by name (without file extension) if it is from current theme or by full path and name if it is custom.

**Comment by kazysmaster** [comment]
workking on it

**Comment by kazysmaster** [comment]
please try the github version.

**Comment by angystardust** [comment]
Fedora31 here: after a shell restart (Atl-f2 if you're on Xorg), works like a charm! :rocket:

**Comment by diegorodriguezv** [comment]
Works amazing in latest version from gnome extensions website.
