### ISSUE TITLE
Error during the installation using both GitHub and Gnome-Extension-Tool

### ISSUE THREAD

**Issue by giacar** [kazysmaster/gnome-shell-extension-lockkeys#73]
Hi, I have a problem after the update of the extension on the Gnome-Extension: the installation gives me error if I install it both using Gnome-Extension and manually downloading though GitHub repo.
In particular the error is about an import:  "imports.gi.Gtk.Keymap is undefined".

![Schermata da 2020-03-11 12-32-53](https://user-images.githubusercontent.com/34303206/76413401-a489e980-6395-11ea-9962-dbb4cb2f4124.png)

My system is Ubuntu 18.04 LTS using GNOME Shell 3.28.4 .
Thank you for the attention.

**Comment by giacar** [comment]
Sorry if I'm so pushy but also with the updates of both GitHub and Gnome-Extension, I have the same error on this imports. 
Thank you for the support and the patience.

**Comment by kazimierasvaina-cujo** [comment]
yeah, it seems that I've made a mistake, it should be imports.gi.Gdk.Keymap.get_default() - I'll fix that in the evening.

**Comment by kazysmaster** [comment]
I submitted fixed version for a review.
