### ISSUE TITLE
Switching from Show/Hide option to other doesn't show icons

### ISSUE THREAD

**Issue by mbirth** [kazysmaster/gnome-shell-extension-lockkeys#78]
When in Show/Hide mode without any lock active (i.e. no icon shown), then switching to one of the other modes, e.g. "Both", doesn't show the indicator icons. Even after toggling one of the lock keys, the icons don't appear.

Only when switching to Show/Hide mode, then enabling on lock so the icon shows up and then switching to one of the other modes, it will work.

**Comment by kazysmaster** [comment]
will be fixed in the next version
