### ISSUE TITLE
Keys shown as disabled after restarting GNOME Shell

### ISSUE THREAD

**Issue by lepa22** [kazysmaster/gnome-shell-extension-lockkeys#79]
Steps to reproduce:
- Have at least one key enabled.
- Restart GNOME Shell.

Result:
- Both keys are shown as disabled, however their state is the same as before restarting GNOME Shell. After hitting one of the keys, the correct state of the keys is shown.

Expected result:
- Keys show their correct state after restarting GNOME Shell.

**Comment by kazysmaster** [comment]
Should be fixed in the next version.

**Comment by lepa22** [comment]
Thank you!
