### ISSUE TITLE
[GNOME 3.38.2] Source.notify() has been moved to Source.showNotification()

### ISSUE THREAD

**Issue by dongsibo** [kazysmaster/gnome-shell-extension-lockkeys#90]
When using compact notifications with Lock Keys on GNOME Wayland, the following message appears in the output of `systemctl --user status org.gnome.Shell@wayland.service` whenever a notification is received from Lock Keys from pressing the `CapsLock` button:
```
Dec 12 18:40:34 flyingpig gnome-shell[11377]: JS ERROR: Error: Source.notify() has been moved to Source.showNotification()this code will break in the future
                                              notify@resource:///org/gnome/shell/ui/messageTray.js:793:23
                                              _showNotification@/usr/share/gnome-shell/extensions/lockkeys@vaina.lt/extension.js:189:17
                                              wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                              _handleStateChange@/usr/share/gnome-shell/extensions/lockkeys@vaina.lt/extension.js:158:18
                                              wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
```
The message does not appear when using OSD notifications. This is the line the error is referring to: [extension.js#L189][1].

Additional info:
- Lock Keys version: b2e67dd, i.e., latest master as of writing
- GNOME Shell version: [`1:3.38.2-1`][2]
- GJS version: [`2:1.66.1-1`][3]

[1]: https://github.com/kazysmaster/gnome-shell-extension-lockkeys/blob/b2e67dd5986c5e2713b0fe037383cb9235dc845d/lockkeys%40vaina.lt/extension.js#L189
[2]: https://www.archlinux.org/packages/extra/x86_64/gnome-shell/
[3]: https://www.archlinux.org/packages/extra/x86_64/gjs/

**Comment by kazysmaster** [comment]
fixed.
