### ISSUE TITLE
Buggy OSD icons

### ISSUE THREAD

**Issue by ActualDisaster2447** [kazysmaster/gnome-shell-extension-lockkeys#97]
Whenever I enable this extension on Gnome 41, it makes the OSDs of volume and brightness controls display the wrong icons. 

**How to reproduce?**
Use the caps lock key and then press volume or brightness control keys. 

**Software**
OS: openSUSE Tumbleweed
DE version: Gnome 41
Icon theme: Adwaita
Shell theme: Adwaita

**Comment by kazysmaster** [comment]
Did the problem went away after updates?
