### ISSUE TITLE
Error starting version 45 on Gnome 3.30

### ISSUE THREAD

**Issue by Phidica** [kazysmaster/gnome-shell-extension-lockkeys#99]
Since the recent update through Gnome Extensions to version 45, the extension does not start on Gnome 3.30.2. Logs show the following error:
```
TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)
```

**Comment by kazysmaster** [comment]
on which distro  I could reproduce it?

**Comment by Phidica** [comment]
Debian Buster. Since then I've updated to Debian Bullseye (Gnome 3.38.6) and I don't have a problem any more. You can probably close this, unless you feel like investigating it anyway :wink:
